context:
  name: carapace
  version: "1.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/carapace-sh/carapace-bin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7eebc2b3f7ac4fb5641612343ce813b2f7e1c0fffd1251255542e9bfbf9ed207
build:
  script:
    - cd cmd/carapace
    - go generate ./...
    - go install
    - if: win
      then: go-licenses save . --save_path %SRC_DIR%/library_licenses
      else: go-licenses save . --save_path $SRC_DIR/library_licenses
  number: 0

requirements:
  build:
    - ${{ compiler('go') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script: carapace --help

about:
  homepage: https://carapace.sh/
  summary: A multi-shell completion binary
  description: |
    Carapace-bin provides argument completion for multiple CLI commands ([full list](https://carapace-sh.github.io/carapace-bin/completers.html)),
    and works across multiple POSIX and non-POSIX shells.
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/
  documentation: https://pixi.carapace.sh/
  repository: https://github.com/carapace-sh/carapace-bin

extra:
  recipe-maintainers:
    - Hofer-Julian
