context:
  name: carapace
  version: "1.7.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/carapace-sh/carapace-bin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7d110560caaa61a5c0966ce8882037b189128b212a83402b0c653d81bd04544d
build:
  script:
    - if: win
      then: set "GOPATH=%TEMP%\gopath"
      else: export GOPATH=$(mktemp -d)
    - cd cmd/carapace
    - if: win
      then:
        - go build -o ..\carapace-generate\carapace-generate.exe ..\carapace-generate
        - ..\carapace-generate\carapace-generate.exe generate-all ..\..\completers
        - ..\carapace-generate\carapace-generate.exe macros --code github.com/carapace-sh/carapace-bin/pkg/actions github.com/carapace-sh/carapace-bridge/pkg/actions github.com/carapace-sh/carapace-jjlex/pkg/actions --output ..\..\pkg\actions\actions_generated.go
        - ..\carapace-generate\carapace-generate.exe conditions ..\..\pkg\conditions --output ..\..\pkg\conditions\conditions_generated.go
    - if: osx and arm64
      then: GOARCH=amd64 go generate ./...
    - if: linux or (osx and not arm64)
      then: go generate ./...
    - if: win
      then:
        - go build -v -ldflags "-w -s -X main.version=${{ version }}" -o %LIBRARY_PREFIX%\bin\carapace.exe .
        - go-licenses save . --save_path %SRC_DIR%/library_licenses
      else:
        - go build -v -ldflags "-w -s -X main.version=${{ version }}" -o $PREFIX/bin/carapace .
        - go-licenses save . --save_path $SRC_DIR/library_licenses
  number: 0

requirements:
  build:
    - ${{ compiler('go') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script: carapace --help

about:
  homepage: https://carapace.sh/
  summary: A multi-shell completion binary
  description: |
    Carapace-bin provides argument completion for multiple CLI commands ([full list](https://carapace-sh.github.io/carapace-bin/completers.html)),
    and works across multiple POSIX and non-POSIX shells.
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/
  documentation: https://pixi.carapace.sh/
  repository: https://github.com/carapace-sh/carapace-bin

extra:
  recipe-maintainers:
    - Hofer-Julian
